version: '3'
services:
  jupyter-environment:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan/work